mtgbrew/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls import (
handler400, handler403, handler404, handler500
)

from brew import views

handler400 = 'brew.views.bad_request'
handler403 = 'brew.views.permission_denied'
handler404 = 'brew.views.page_not_found'
handler500 = 'brew.views.server_error'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^feedback/', views.search, name='feedback'),
    url(r'^$', views.deck_builder, name ='deck-builder'),
    url(r'^(?P<username>\w+)/my-decks', views.my_decks, name='my-decks'),
    url(r'^deck/(?P<pk>\d+)/$', views.deck_view, name ='deck-view'),
    url(r'^deck/(?P<pk>\d+)/edit/$', views.deck_edit, name="deck-edit"),
    url(r'^deck/(?P<pk>\d+)/delete/$', views.deck_delete, name="deck-delete"),
    url(r'^accounts/', include('allauth.urls')),]

brew/models.py
# Django libraries
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.forms import ModelForm
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.conf import settings

# Third-Party libraries
from redactor.fields import RedactorField

# Python libraries
import json
import re
import time
import urllib2
import datetime

# Create your models here.

# Definiition for a deck
# Contains a series of Playset models for the mainboard and sideboard
# Contains deck prices, and other important deck details
# Check variable names for a description on the data contained in the Deck Model

GAME_FORMATS = (
		('STD', 'Standard'),
		('MDN', 'Modern'),
		('LGC', 'Legacy'),
		('VTG', 'Vintage'),
		('EDH', 'Commander/EDH'),
		('PAU', 'Pauper'),
	)

DECK_PRIVACY = (
		('PUB', 'Public'),
		('PRV', 'Private'),
		('UNL', 'Unlisted'),
	)

digital_data_buffer = []
paper_data_buffer = []
paper_data_by_line = []
card_data_by_line = []

# Initial Data population
cardhoarder_data_url = "https://www.cardhoarder.com/affiliates/pricefile/480166"
isleofcards_data_url = "https://www.isleofcards.com/files/prices.txt"
paper_data = urllib2.urlopen(isleofcards_data_url)
mtgo_data = urllib2.urlopen(cardhoarder_data_url)
card_data = set(mtgo_data.read().splitlines())
paper_card_data = set(paper_data.read().splitlines())

for line in card_data:
	digital_data_buffer.append(line.split('\t'))

for line in paper_card_data:
	paper_data_buffer.append(line.split('\t'))

paper_data_by_line = paper_data_buffer
card_data_by_line = digital_data_buffer

class Deck(models.Model):
	deck_name = models.CharField(max_length=200, blank=False)
	deck_format = models.CharField(max_length=50, choices=GAME_FORMATS, blank=False)
	deck_price_paper = models.IntegerField(validators=[MinValueValidator(0)], default=0)
	deck_price_online = models.IntegerField(validators=[MinValueValidator(0)], default=0)
	deck_privacy = models.CharField(max_length=20, choices=DECK_PRIVACY, blank=False)
	deck_need_feedback = models.BooleanField(blank=True)
	deck_rating	= models.IntegerField()
	deck_last_edited = models.DateTimeField()
	deck_tags = models.CharField(blank=True, max_length=200)
	deck_description = RedactorField(verbose_name=u'Deck Description')
	decklist_mainboard = models.CharField(max_length=1000, blank=False)
	decklist_sideboard = models.CharField(max_length=1000, blank=True)
	deck_owner = models.ForeignKey(settings.AUTH_USER_MODEL, default=None)

class PaperCardStore(models.Model):
	paper_store = ArrayField(models.CharField(max_length=200, blank=True), size=None, blank=True)

class DigitalCardStore(models.Model):
	digital_store = ArrayField(models.CharField(max_length=200, blank=True), size=None, blank=True)

class Card(models.Model):
	card_name = models.CharField(max_length=200, blank=False)
	card_price_paper = models.DecimalField(validators=[MinValueValidator(0)], default=0.00, max_digits=6, decimal_places=2)
	card_price_online = models.DecimalField(validators=[MinValueValidator(0)], default=0.00, max_digits=6, decimal_places=2)

class DeckForm(ModelForm):
	class Meta:
		model = Deck
		fields = [	'deck_name', 'deck_format', 'deck_description', 'deck_privacy', 'deck_need_feedback', 
					'deck_tags', 'decklist_mainboard', 'decklist_sideboard']

	# Custom validation to clean the mainboard from
	#		the deck builder view
	def clean_decklist_mainboard(self):
		# Get price data
		card_data_by_line = DigitalCardStore.objects.values_list('digital_store', flat=True)
		paper_data_by_line = PaperCardStore.objects.values_list('paper_store', flat=True)

		# Reset deck price
		self.instance.deck_price_online = 0
		self.instance.deck_price_paper = 0
		
		# Grab decklist from the form
		mainboard_buffer = self.cleaned_data.get('decklist_mainboard')

		# Check that the mainboard actually contains cards
		if mainboard_buffer == "" or mainboard_buffer == None:
			raise ValidationError(_("Your mainboard must contain cards"), code='EmptyList')
		else:
			self.parse_board(mainboard_buffer)

		return mainboard_buffer

	def clean_decklist_sideboard(self):
		sideboard_buffer = self.cleaned_data.get('decklist_sideboard')

		# Verify that the sideboard contains cards
		if sideboard_buffer == "" or sideboard_buffer == None:
			return sideboard_buffer
		else:
			self.parse_board(sideboard_buffer)

		return sideboard_buffer

	def parse_board(self, deck_board):
		print "Beginng board clean"
		print paper_data_by_line
		parsed_deck_board = deck_board.split('\n')
		verified_current_card_digital = None
		verified_current_card_paper = None

		print card_data_by_line

		# Iterate through mainboard and check if card exists
		for line in parsed_deck_board:
			# Check if mainboard is formatted correctly
			# If yes, check if card exists
			# Else, raise an error
			try:
				current_card = str(line.split(" ", 1)[1]).strip()
				current_card_quantity = int(line.split(" ", 1)[0])
			except:
				raise ValidationError("Please provide an amount for each card entry. Example: \n 1 Storm Crow")
			else:
				# Search vendor data for card
				for sublist in card_data_by_line:
					# If the card exists, grab it's dataset
					if current_card.lower() in (sublist_card.lower() for sublist_card in sublist):
						verified_current_card_digital = sublist
						break

				for sublist in paper_data_by_line:
					if current_card.lower() in (sublist_card.lower() for sublist_card in sublist):
						verified_current_card_paper = sublist
						break

				# If the card doesn't exist, return a Validation Error
				# Else, find price, and add it to the total
				if verified_current_card_digital is None:
					raise ValidationError("Cannot find card: " + current_card)
				else:
					self.instance.deck_price_online += float(verified_current_card_digital[5]) * current_card_quantity

				if verified_current_card_paper is None:
					raise ValidationError("Cannot find card: " + current_card)
				else:
					self.instance.deck_price_paper += float(verified_current_card_paper[5]) * current_card_quantity

brew/views.py
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
# Django imports
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader, RequestContext
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.views.defaults import page_not_found

# Model imports
from models import DeckForm, Deck, Card, DeckForm
from django.contrib.auth.models import User

from brew import tasks

# Python imports
import urllib2
import json
from operator import itemgetter

# Python library imports
import pygal
from pygal.style import Style

# Load MTGJSON into memory
mtgjson_filepath = "brew/static/brew/AllCards.json"
mtgjson_data = json.load(open(mtgjson_filepath))

mtg_color_pie = {
	"White": '#fff6aa',
	"Blue": '#308af2',
	"Black": '#000000',
	"Red": '#e20f0f',
	"Green": '#29bc1c',
	"Colorless": '#9b744a'
}

# Chart Styles
mtg_colour_style = Style(
	transition='400ms ease-in',
  	colors=(mtg_color_pie['White'], mtg_color_pie['Blue'], mtg_color_pie['Black'], mtg_color_pie['Red'],
  	 		mtg_color_pie['Green'], mtg_color_pie['Colorless']),
  	background="transparent",
  	font_family="Arial",
  	label_font_size=25,
  	title_font_size=25,
  	legend_font_size=25,
  	tooltip_font_size=25
  	)

general_style = Style(
	transition='400ms ease-in',
  	background="transparent",
  	font_family="Arial",
  	label_font_size=25,
  	title_font_size=25,
  	legend_font_size=25,
  	tooltip_font_size=25
  	)


def bad_request(request):
	response = render_to_response(
		'brew/500.html',
		context_instance=RequestContext(request)
		)

	response.status_code = 400

	return response

def permission_denied(request):
	response = render_to_response(
		'brew/500.html',
		context_instance=RequestContext(request)
		)

	response.status_code = 403

	return response

def page_not_found(request):
	response = render_to_response(
		'brew/404.html',
		context_instance=RequestContext(request)
		)

	response.status_code = 404

	return response

def server_error(request):
	response = render_to_response(
		'brew/500.html',
		context_instance=RequestContext(request)
		)

	response.status_code = 500

	return response

# Create your views here
def search(request):
	return render(request, 'brew/deck-search.html')

def my_decks(request, username):
	current_user = User.objects.get(username=username)
	user_decks = current_user.deck_set.all()

	return render(request, 'brew/my-decks.html', {'user_decks': user_decks, 'current_user': current_user})

def deck_view(request, pk):

	# Check CMC values from min CMC to max CMC in list
	# CMC values in decks go from 0 to x
	# This reflects the order for elements in a list
	def sort_cmc_by_color(color):
		new_cmc = []
		for i in range(0, (deck_cmc_list[-1] + 1)):
			# Create empty entry for insertion
			new_cmc.append(None)
			# Check if any CMCs match the current CMC value to check
			for cmc in card_cmc_lists[color]:
				# If a match is found, try to add to current CMC count
				# Otherwise, insert value as initial count
				if cmc[0] == i:
					try:
						new_cmc[i] += cmc[1]
					except:
						new_cmc[i] = cmc[1]

		return new_cmc

	deck = get_object_or_404(Deck, pk=pk)
	tasks.update_deck_cost(deck)

	current_user_string = str(request.user.get_username())
	deck_owner_string = str(deck.deck_owner)

	# Get card data for decklist
	# Counters for card types
	creature_count = 0
	enchantment_count = 0
	instant_count = 0
	artifact_count = 0
	planeswalker_count = 0
	sorcery_count = 0
	land_count = 0

	card_type_counts = {"Creature": 0,
				"Enchantment": 0,
				"Instant": 0,
				"Artifact": 0,
				"Planeswalker": 0,
				"Sorcery": 0,
				"Land": 0}

	# List of all CMCs
	deck_cmc_list = []

	# Dictionary containing list of color-sorted CMCs
	card_cmc_lists = { "W": [],
				"U": [],
				"B": [],
				"R": [],
				"G": [],
				"C": []}

	card_color_distribution = { "W": 0,
				"U": 0,
				"B": 0,
				"R": 0,
				"G": 0,
				"C": 0}

	# Parse Decklist for lookups
	parsed_decklist = deck.decklist_mainboard.split('\n')

	# Parse Decklist for URL
	url_decklist = deck.decklist_mainboard.replace('\n', '||') + '||' + deck.decklist_sideboard.replace('\n', '||')

	# Attempt to generate graphs
	try:
		for line in parsed_decklist:
			if line is not "" or line is not None:
				
				current_card = str(line.split(" ", 1)[1]).strip()
				current_card_quantity = int(line.split(" ", 1)[0])
				
				for key, value in card_type_counts.iteritems():
					if key in mtgjson_data[current_card]['types']:
						card_type_counts[key] += current_card_quantity
					

				# Check for card colours and aggregate 
				# Check if card has Color Identity to account for lands 
				if 'Land' not in mtgjson_data[current_card]['types']:

					# Count mana symbols in each card's cost
					for key, value in card_color_distribution.iteritems():
						card_color_distribution[key] += mtgjson_data[current_card]['manaCost'].count(key) * current_card_quantity

					# If the card has a color ID then proceed
					# Otherwise, it's colorless
					if mtgjson_data[current_card].has_key('colorIdentity'):	
						for key, value in card_cmc_lists.iteritems():		
							if key in mtgjson_data[current_card]['colorIdentity']:

								# Attempt to retreive the CMC
								# If no CMC, set CMC to 0
								try:
									current_card_cmc = mtgjson_data[current_card]['cmc']
									deck_cmc_list.append(current_card_cmc)
									cmc_info = (current_card_cmc, current_card_quantity)
									card_cmc_lists[key].append(cmc_info)
								except:
									current_card_cmc = 0
									deck_cmc_list.append(current_card_cmc)
									cmc_info = (current_card_cmc, current_card_quantity)
									card_cmc_lists[key].append(cmc_info)
					else:
						try:
							current_card_cmc = mtgjson_data[current_card]['cmc']
							deck_cmc_list.append(current_card_cmc)
							cmc_info = (current_card_cmc, current_card_quantity)
							card_cmc_lists['C'].append(cmc_info)
						except:
							current_card_cmc = 0
							deck_cmc_list.append(current_card_cmc)
							cmc_info = (current_card_cmc, current_card_quantity)
							card_cmc_lists['C'].append(cmc_info)

	except:
		print "Error parsing graph data"
		
	deck_cmc_list.sort()

	# Create chart of card types
	cardtype_piechart = pygal.Pie(style=general_style)
	cardtype_piechart.title = "Card Type Breakdown"

	for key, value in card_type_counts.iteritems():
		if value > 0:
			cardtype_piechart.add(key, value)

	cardcolor_piechart = pygal.Pie(style=mtg_colour_style)
	cardcolor_piechart.title = "Deck Colours Breakdown (by Mana Symbols)"
	cardcolor_piechart.add("White", card_color_distribution["W"])
	cardcolor_piechart.add("Blue", card_color_distribution["U"])
	cardcolor_piechart.add("Black", card_color_distribution["B"])
	cardcolor_piechart.add("Red", card_color_distribution["R"])
	cardcolor_piechart.add("Green", card_color_distribution["G"])
	cardcolor_piechart.add("Colorless", card_color_distribution["C"])

	# Create CMC bar chart
	cmc_barchart = pygal.StackedBar(style=mtg_colour_style)
	cmc_barchart.title = "Mana Curve"
	cmc_barchart.x_labels = map(str, range(0, deck_cmc_list[-1] + 1))
	cmc_barchart.add("White", sort_cmc_by_color("W"))
	cmc_barchart.add("Blue", sort_cmc_by_color("U"))
	cmc_barchart.add("Black", sort_cmc_by_color("B"))
	cmc_barchart.add("Red", sort_cmc_by_color("R"))
	cmc_barchart.add("Green", sort_cmc_by_color("G"))
	cmc_barchart.add("Colorless", sort_cmc_by_color("C"))

	return render(request, 'brew/deck-view.html', {'deck': deck, 'cardcolor_chart': cardcolor_piechart.render(), 
											'cardtype_chart': cardtype_piechart.render(), 
											'cmc_chart': cmc_barchart.render(),
											'url_decklist': url_decklist,
											'current_user': current_user_string,
											'deck_owner': deck_owner_string})

@login_required
def deck_builder(request):
	if request.method == "POST":
		# Save Data
		form = DeckForm(request.POST)

		if form.is_valid():
			deck = form.save(commit=False)
			deck.deck_rating = 0
			deck.deck_owner = request.user
			deck.deck_last_edited = timezone.now()
			deck.deck_need_feedback = False

			deck.save()

			return redirect('deck-view', pk=deck.pk)

		else:
			print("INVALID FORM")

	else:
		# Load empty form
		form = DeckForm()

	return render(request, 'brew/deck-builder.html', {'form': form})

@login_required
def deck_edit(request, pk):
	deck = get_object_or_404(Deck, pk=pk)

	if request.method == "POST":
		form = DeckForm(request.POST, instance=deck)

		if form.is_valid():
			deck = form.save(commit=False)
			deck.author = request.user
			deck.deck_last_edited = timezone.now()
			deck.save()

			return redirect('deck-view', pk=deck.pk)

	else:
		form = DeckForm(instance=deck)

	return render(request, 'brew/deck-builder.html', {'form': form})

def deck_delete(request, pk):
	deck = get_object_or_404(Deck, pk=pk)

	# If the user owns the deck, allow them delete
	if deck.deck_owner == request.user:
		deck.delete()
		return redirect('my-decks', username=request.user)

	else:
		raise Http404

brew/templates/brew/base.html
<meta name="viewport" content="width = device-width, initial-scale = 1">
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<script src="https://use.fontawesome.com/2104d4014e.js"></script>
<script src="{% static 'js/tooltip.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'brew/bootstrap-social.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'brew/base.css' %}">

<title>MTGBrew</title>
<header id="masthead" class="site-header" role="banner">
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">MTGBrew <sub id="beta-tag">Beta</sub></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Deck Builder</a></li>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
          <li></li>
          <li><a href="/feedback/">Feedback</a></li>
        {% if user.is_authenticated %}
          <li><a href="/{{request.user}}/my-decks">My Decks</a></li>
          <li><a href="/accounts/logout">Logout</a></li>

        {% else %}
          <li><a href="/accounts/login">Login/Register</a></li>

        {% endif %}

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

<content>
<body>
<div class="container">
{% block content %}
{% endblock %}
</div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</body>
</content>
<div id="footer" class="well">
  <footer> <p align="center">Magic: the Gathering is copyright of Wizards of the Cost, Inc, a subsidiary of Hasbro, Inc. All rights reserved. This site is unaffiliated. Articles and content are user-created and do not represent official endorsement of this site.<br><br>

  Having issues? Please send an email to mtgbrew@gmail.com and we'll look into it!
  </p></footer>
</div>

brew/templates/brew/deck-search.html
{% extends "brew/base.html" %}
{% block content %}

{# Import Style Sheet for Deck Searching #}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'brew/search.css' %}" />

{# Container to provide padding on the edges #}
<div class="container">

	<div name="search-parameters" class="well">

		<h3 align="center">We Love Feedback!</h3>
		<p align="center"> Your feedback is essential for us to provide you with the best possible deck building experience.
			<br>
			Let us know what you think by sending an email to mtgbrew@gmail.com. Thanks for the support and we look forward to hearing from you!
		</p>
	</div><!-- /.search-parameters -->
</div><!-- /.container -->

{% endblock %}

brew/templates/brew/deck-view.html
{% extends "brew/base.html" %}
{% block content %}

{# Import Style Sheet for Deck Searching #}
{% load static %}
<head>
	<script src="{% static 'js/custom_tappedout_deckview.js' %}"></script>
	<link rel="stylesheet" href="{% static 'brew/decklist-formatting.css' %}">
</head>

<div class="container">
<div class="deck-details">

	{# Contains basic deck info. E.G: Name, author, price etc #}
	{# Aligned top-left #}
	{% if current_user == deck_owner or deck.deck_privacy != "PRV" %}
	<div class="deck-header">
	<div class="row" name="content">
		
	</div> <!-- Deck Header Row END -->
	</div> <!-- ./deck-header -->

	{# Displays the deck list. Formatting determined by widget in deck-header #}
	{# Has affiliate links located underneath #}
	{# Aligned mid-left #}
	<div class="row" name="decklist-details">
		<div class="col-lg-8">
			<div class="well">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
					<h2>{{ deck.deck_name }} <small>by <a href="/{{ deck.deck_owner }}/my-decks">{{deck.deck_owner}}</a> </small></h2>
				</div> <!-- Deck Name & Author -->
			</div> <!-- Heading -->

			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
					<p>Deck Price (Online): {{ deck.deck_price_online }} </p>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
					<p>Deck Price (Paper): {{ deck.deck_price_paper }} </p>
				</div>
			</div> <!-- Deck Prices -->

			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
					<p>{{deck.get_deck_format_display}}</p>
				</div>
				<div class="col-lg-4 col-md-8 col-sm-6 col-xs-12">
					<p>Tags: {{deck.deck_tags}}</p>
				</div>
			</div><!-- Format & Tags -->

			<div style="padding-bottom: 10px">
				{% if current_user == deck_owner %}
					<a class="btn btn-info" href="/deck/{{deck.pk}}/edit">Edit Deck</a>
				{% endif %}
			</div><!-- Edit Button-->
			<small>Last Edited: {{ deck.deck_last_edited }}</small>

			<div class="contents-divider">
	          <hr class="hr-or">
	        </div>

			<div class="row" name="decklist">
				<div class="deck-list">
					{{deck.decklist_mainboard}}

					Sideboard|sideboard|Sideboard:
					{{deck.decklist_sideboard}}
				</div>
			</div>

			<div class="row" name="affiliate-links">
				<div class="col-sm-4">
				<form method="POST" action="https://www.cardhoarder.com/decks/upload?affiliate_id=twoo&deck={{url_decklist}}">
					<button type="submit" class="btn btn-warning"><span class="glyphicon glyphicon-shopping-cart"></span> Buy on Cardhoarder</button>
				</form>
				</div>

				<div class="col-sm-4">
				<form method="POST" action="https://www.isleofcards.com/decks/upload?affiliate_id=twoo&deck={{url_decklist}}">
					<button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-shopping-cart"></span> Buy on Isle of Cards</button>
				</form>
				</div>
			</div>
			</div><!-- End deck contents well -->

			<div class="well">
				<div class="row" name="deck description">
					<h3>Description</h3>
					{{deck.deck_description|safe}}	
				</div>
			</div>			
		</div>

		<div class="col-lg-4">
			<div class="well">
				<div class="row" name="color_chart">{{cardcolor_chart|safe}}</div>
				<div class="row" name="type_chart">{{cardtype_chart|safe}}</div>
				<div class="row" name="cmc_chart">{{cmc_chart|safe}}</div>
			</div>
		</div>
	</div>
	</div><!-- End of deck contents & graphs-->
	</div>

	{% else %}
	<div class="well">
		<p align="center"> Sorry, this deck is private and cannot be viewed at the moment. If you are the owner of the deck, make sure you are logged in </p>
	</div>

	{% endif %}

</div> <!-- ./deck-details -->
</div> <!-- ./container -->

{% endblock %}

brew/templates/brew/my-decks.html
{% extends "brew/base.html" %}
{% block content %}

<div class="container">

<div class="jumbotron">

	<h3>{{ current_user }}'s Decks</h3>

	<br>

	{% for deck in user_decks %}
	{% if deck.deck_privacy == "PUB" or request.user == deck.deck_owner%}
	<div class="row">
		<div class="contents-divider">
	      <hr class="hr-or">
	    </div>
		<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
		<dl>
			<dt> <a href="/deck/{{deck.pk}}">{{ deck.deck_name }}</a> </dt>
			<dd> Price (Online): {{ deck.deck_price_online }} | Price (Paper): {{ deck.deck_price_paper }} </dd>
			<dd> Tags: {{ deck.deck_tags }} </dd>
		</dl>
		</div>

		<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
			Format: {{ deck.get_deck_format_display }}
		</div>

	{% ifequal request.user deck.deck_owner %}
		<div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
			<a class="btn btn-info" href="/deck/{{deck.pk}}/edit">Edit</a>
		</div>

		<div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
			<a class="btn btn-danger confirm-delete" href="/deck/{{deck.pk}}/delete" onclick="return confirm('Are you sure you want to delete this?')">Delete</a>
		</div>
	{% endifequal %}
	
	</div>
	{% endif %}
	{% endfor %}

</div>

</div>

{% endblock %}